// mobile/src/ui/ExportPanel.tsx
import { Text, View } from 'react-native';

import { Button } from './Button';

export type ExportFormat = 'csv' | 'zip';

interface Props {
  /** Undefined while the count is still loading. */
  count: number | undefined;
  zipCap: number;
  /** The format currently being minted, if any. */
  pending: ExportFormat | null;
  onExport: (format: ExportFormat) => void;
}

/**
 * Exports what the Library is showing.
 *
 * Presentational. The count is advisory - the server recounts at mint and again
 * at download - so this only decides what to *offer*; it never decides what is
 * allowed.
 */
export function ExportPanel({ count, zipCap, pending, onExport }: Props) {
  // Rendering "0 images match" before the count arrives would briefly tell the
  // user there is nothing to export.
  if (count === undefined) return null;

  const empty = count === 0;
  const zipTooLarge = count > zipCap;
  const busy = pending !== null;

  return (
    <View className="mb-4 gap-3 rounded-surface border border-border-strong bg-surface-raised p-3">
      <Text className="text-section text-text">
        {count} {count === 1 ? 'image matches' : 'images match'}
      </Text>

      <View className="flex-row gap-2">
        <Button
          label="Export CSV"
          variant="secondary"
          flex={1}
          pending={pending === 'csv'}
          disabled={empty || busy}
          onPress={() => onExport('csv')}
        />
        {/* Disabled over the cap rather than left pressable for the server to
            refuse: the reason belongs beside the button before it is pressed. */}
        <Button
          label="Export ZIP"
          variant="secondary"
          flex={1}
          pending={pending === 'zip'}
          disabled={empty || zipTooLarge || busy}
          onPress={() => onExport('zip')}
        />
      </View>

      {zipTooLarge ? (
        <Text className="text-meta text-danger-text">
          A ZIP is limited to {zipCap} images. Narrow the filter to export one — the CSV has no
          limit.
        </Text>
      ) : (
        // Not buried: the download leaves the app, and a ZIP of this many images
        // is fetched from Wikimedia and resized before it starts.
        <Text className="text-meta text-text-muted">
          Exports open in your browser. A ZIP can take a minute or two to start.
        </Text>
      )}
    </View>
  );
}

// web/src/components/ExportPanel.vue
<script setup lang="ts">
import type { ExportFormat } from '@/api/composables/useExport';
import { ZIP_CAP } from '@/config';

import BaseButton from './BaseButton.vue';

/**
 * Presentational. The count is advisory - the server recounts at mint and at
 * download - so this decides what to offer, never what is allowed.
 */
const props = withDefaults(
  defineProps<{ count: number | undefined; pending: ExportFormat | null; zipCap?: number }>(),
  { zipCap: ZIP_CAP },
);
const emit = defineEmits<{ export: [format: ExportFormat] }>();

const tooLargeForZip = () => (props.count ?? 0) > props.zipCap;
</script>

<template>
  <div class="flex flex-wrap items-center gap-x-4 gap-y-2">
    <p class="text-body text-ink-2" aria-live="polite">
      <template v-if="count === undefined"><span class="skeleton inline-block h-4 w-24 rounded align-middle" /></template>
      <template v-else>
        <span class="type-figure text-ink">{{ count.toLocaleString('en') }}</span>
        {{ count === 1 ? 'image matches' : 'images match' }}
      </template>
    </p>
    <div class="flex gap-2">
      <BaseButton
        variant="secondary"
        size="sm"
        icon="download"
        :pending="pending === 'csv'"
        :disabled="!count || pending !== null"
        @click="emit('export', 'csv')"
      >
        Export CSV
      </BaseButton>
      <BaseButton
        variant="secondary"
        size="sm"
        icon="download"
        :pending="pending === 'zip'"
        :disabled="!count || tooLargeForZip() || pending !== null"
        :title="tooLargeForZip() ? `A ZIP holds at most ${zipCap} images` : undefined"
        :aria-describedby="tooLargeForZip() ? 'zip-cap-note' : undefined"
        @click="emit('export', 'zip')"
      >
        Export ZIP
      </BaseButton>
    </div>
    <p v-if="tooLargeForZip()" id="zip-cap-note" class="basis-full text-meta text-ink-3">
      A ZIP holds at most {{ zipCap }} images. Narrow the filters to export one; the CSV has no limit.
    </p>
  </div>
</template>
